# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jiawei Zhao
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zhaojwvsmike@outlook.com
      link: mailto:zhaojwvsmike@outlook.com
    - name: WeChat
      value: u_r_muted
      link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/RealJiaweiZhao
      username: "@RealJiaweiZhao"
    - name: LinkedIn
      link: http://linkedin.com/in/zhao-jiawei-72526b144
    - name: GitHub
      link: http://github.com/zjw1990


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
